version: '3.1'

services:

  quiz-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_URL=${DB_URL}
        - DB_USERNAME=${DB_USER_NAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - FLYWAY_ENABLED=${FLYWAY_ENABLED}
    ports:
      - "8080:8080"